language: python
branches:
  only:
    - master
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.5-dev
  - 3.6-dev
  - 3.7-dev
install: 
  - pip install coverage coveralls 
  - export PYTHONPATH=$PWD/p3270
script:
  - cd p3270/test
  - coverage run test_p3270.py
after_success:
  - coveralls
